{{ if .Values.content.git.deployKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ .Values.content.git.deployKey | quote }}
{{ end }}
