{{- if .Values.deploy.statefulSet }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "nginx.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage:  {{ .Values.content.volume.size }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nginx.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "nginx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.content.enabled }}
      initContainers:
        - name: content-init
          image: {{ .Values.content.SyncImage.repository }}:{{ .Values.content.SyncImage.tag }}
          {{- if .Values.content.SyncImage.command }}
          command: [ {{ .Values.content.SyncImage.command | quote }} ]
          {{- end }}
          {{- if .Values.content.SyncImage.args }}
          args:
          {{- range .Values.content.SyncImage.args }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
          env:
            - name: LOOP_FOREVER
              value: "false"
            - name: INITIAL_RUN
              value: "true"
          {{- if .Values.content.git.repository }}
            - name: GIT_BRANCH
              value: {{ .Values.content.git.branch | quote }}
            - name: SRC_URL
              value: {{ .Values.content.git.repository | quote }}
          {{- end }}
          volumeMounts:
            - name: www
              mountPath: /workspace
              readOnly: false
            {{- if .Values.content.git.deployKey }}
            - name: idrsa
              mountPath: /root/.githubkeys
              readOnly: true
            {{- end }}
      {{- end }}
      containers:
      {{- if .Values.content.enabled }}
        - name: content-sync
          image: {{ .Values.content.SyncImage.repository }}:{{ .Values.content.SyncImage.tag }}
          {{- if .Values.content.SyncImage.command }}
          command: [ {{ .Values.content.SyncImage.command | quote }} ]
          {{- end }}
          {{- if .Values.content.SyncImage.args }}
          args:
          {{- range .Values.content.SyncImage.args }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
          env:
            - name: INITIAL_RUN
              value: "false"
            - name: LOOP_FOREVER
              value: {{ .Values.content.loop_forever | quote }}
            - name: SLEEP_TIME
              value: {{ .Values.content.sleep_time | quote }}
          {{- if .Values.content.git.repository }}
            - name: GIT_BRANCH
              value: {{ .Values.content.git.branch | quote }}
            - name: SRC_URL
              value: {{ .Values.content.git.repository | quote }}
          {{- end }}
          volumeMounts:
            - name: www
              mountPath: /workspace
              readOnly: false
            {{- if .Values.content.git.deployKey }}
            - name: idrsa
              mountPath: /root/.githubkeys
              readOnly: true
            {{- end }}
        {{- end }}
        - name: nginx
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
              readOnly: true
              subPath: "website/{{ .Values.content.path }}"
      volumes:
      - name: local-www
        emptyDir: {}
      {{- if or .Values.content.git.deployKey .Values.content.git.deploySecret }}
      - name: idrsa
        secret:
          secretName: {{ default (include "nginx.fullname" .) .Values.content.git.deploySecret }}
          defaultMode: 0400
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
